### ISSUE TITLE
Localization for "InterstellarMeshSwitch" are not processed correctly

### ISSUE THREAD

**Issue by Galenmacil** [SuicidalInsanity/Mk2Expansion#24]
In game, for multi-mesh parts, instead of proper titles for each mesh, it ends up showing #LOC_M2X_* localization strings.

**Comment by yalov** [comment]
Check `InterstellarFuelSwitch\Localization\Fields\*.cfg` file. Do you have it?

**Comment by yalov** [comment]
More precisely, it's not about parts' right-click menu, but right-click at item in category list. 
MeshSwitch list Items are #LOC_M2X_*
