### ISSUE TITLE
mk2-usils.cfg improperly formatted.

### ISSUE THREAD

**Issue by TenchuHawke** [SuicidalInsanity/Mk2Expansion#44]
NEEDS section seems to be formatted improperly

> @PART[M2X_SmallLab]NEEDS:[USILifeSupport]FOR:[Mk2Expansion]

I think it should be: 
> @PART[M2X_SmallLab]:NEEDS[USILifeSupport] :FOR[Mk2Expansion]

(The colons before the NEEDS and FOR)

Saw an error in MM.  

>[ModuleManager] Cannot parse node name as tag list: tag can't start with [
on: Mk2Expansion/Patches/MK2-USILS/@PART[M2X_SmallLab]NEEDS:[USILifeSupport]FOR:[Mk2Expansion]

**Comment by NachtRaveVL** [comment]
Also note that the newer USILifeSupport (for 1.6.1) now uses a different module name. Name should now read:

```
		name = USILS_LifeSupportRecyclerSwapOption
```
