### ISSUE TITLE
v1.8.4 Squawk List

### ISSUE THREAD

**Issue by TonkaCrash** [SuicidalInsanity/Mk2Expansion#48]
Going through the KSP.log the following issues pop up (in order in log, definitely not order of importance)

1. Parts/Engines/LiftFan/Fuselage - BoxColliders does not support negative scale or size. The effective box size has been forced positive and is likely to give unexpected collision geometry.
2. Patches/Mk2X_WindowShine.cfg - should have :NEEDS[] for all parts for whatever mod provides MODULE[TRReflection]
3. Parts/Engines/IonEngine/part.cfg cannot find textures - They are named incorrectly. Model000 -> mk2IonGrid : Model001 -> MK2IonGrid_Emit
4. Parts/Engines/LiftFan/stack.cfg - M2X_LiftFan - ModuleB9PartSwitch Subtype Radial has no transform named Engine_mount - mismatch between .cfg file and model?
5. M2X_Pluto, M2X_AtomicJet warning only that part cost is less than cost of resources. Cost of these parts should be increased.
6. Parts/Engines/VTOL/part.cfg - M2X_HeavyVTOL ModuleB9PartSwitch Subtype Fuselage Mount No attach nodes matching 'node_stack_bottom' - Misnamed node?
7. Parts/Utility/OMS/omsEngine.cfg - M2X_OMS - source Squad part for textures was deprecated and moved at 1.7, so engine bells appear white
8. Patches/Mk2X_NFE_Functionality.cfg and Patches/M2X_KA.cfg have syntax errors with two separate :NEEDS[], i.e  :NEEDS[first], NEEDS[second] should be :NEEDS[first,second]
9. Patches/MK2-USILS.cfg is built on old version of USI and will not function in current release.
10. Patches/M2X_Tweakscale.cfg duplicates, but is different than patches included in TweakScale. Patches do include % on the MODULE line to add or change, but also need % on the type and defaultScale lines. As is the patches will add duplicate entries if they are run after other TweakScale patches for these parts.
11. Command pods should be updated to include CONTROLPOINT functionality added in 1.6 release of KSP.

**Comment by SuicidalInsanity** [comment]
Thank you for the list. Issues fixed v1.8.4.1.
